//! Hide only when a foreground window covers the bot's monitor, not when merely maximized.
use std::{thread,time::Duration,sync::atomic::Ordering};
use tauri::{AppHandle,Manager};
use windows::Win32::{Foundation::RECT, Graphics::Gdi::{GetMonitorInfoW,MonitorFromWindow,MONITORINFO,MONITOR_DEFAULTTONEAREST},UI::WindowsAndMessaging::{GetClassNameW,GetForegroundWindow,GetWindowRect,IsIconic}};
fn covers(window:&RECT,monitor:&RECT)->bool {(window.left-monitor.left).abs()<=3&&(window.top-monitor.top).abs()<=3&&(window.right-monitor.right).abs()<=3&&(window.bottom-monitor.bottom).abs()<=3}
pub fn start(app:AppHandle){thread::spawn(move||{let mut hidden=false;loop{thread::sleep(Duration::from_millis(700));let Some(win)=crate::island::window(&app)else{continue};let Ok(raw)=win.hwnd()else{continue};let own=windows::Win32::Foundation::HWND(raw.0);let enabled=app.state::<crate::Shared>().settings.lock().unwrap().bar.hide_fullscreen;
let fullscreen=unsafe{let fg=GetForegroundWindow();let mut class=[0u16;256];let len=GetClassNameW(fg,&mut class).max(0)as usize;let class=String::from_utf16_lossy(&class[..len]);if fg.is_invalid()||fg==own||IsIconic(fg).as_bool()||matches!(class.as_str(),"Progman"|"WorkerW"|"Shell_TrayWnd"|"Shell_SecondaryTrayWnd"){false}else{let monitor=MonitorFromWindow(fg,MONITOR_DEFAULTTONEAREST);let own_monitor=MonitorFromWindow(own,MONITOR_DEFAULTTONEAREST);let mut info=MONITORINFO{cbSize:std::mem::size_of::<MONITORINFO>()as u32,..Default::default()};let mut rect=RECT::default();monitor==own_monitor&&GetMonitorInfoW(monitor,&mut info).as_bool()&&GetWindowRect(fg,&mut rect).is_ok()&&covers(&rect,&info.rcMonitor)}};
let should=enabled&&fullscreen;if should!=hidden{hidden=should;if hidden{let _=win.hide();}else if !crate::integrations::PAUSED.load(Ordering::Relaxed){let _=win.show();}}}});}
#[cfg(test)]mod tests{use super::*;#[test]fn distinguishes_maximized_and_fullscreen(){let screen=RECT{left:0,top:0,right:1920,bottom:1080};assert!(covers(&screen,&screen));assert!(!covers(&RECT{bottom:1040,..screen},&screen));assert!(!covers(&RECT{left:1920,right:3840,..screen},&screen));}}
