import assert from 'node:assert/strict';
import { build } from 'esbuild';

const timers = [];
globalThis.window = { setTimeout: (fn) => (timers.push(fn), timers.length), clearTimeout: () => {} };
const result = await build({ stdin: {
  contents: 'export { handleHook, handleCodexLive } from "./src/island/hooks"; export { State } from "./src/core/state"; export { Bridge } from "./src/core/bridge";',
  resolveDir: process.cwd(), loader: 'ts',
}, bundle: true, write: false, platform: 'node', format: 'esm' });
const { handleHook, handleCodexLive, State, Bridge } = await import(`data:text/javascript;base64,${Buffer.from(result.outputFiles[0].text).toString('base64')}`);
const declined = [], acked = [];
Bridge.approvalDecline = async id => { declined.push(id); };
Bridge.approvalAck = async id => { acked.push(id); };
const island = { alert() {}, reveal() {}, setView() {}, dropPin() {} };
State.loadIntegrationTasks();
const claude = State.tasks.find(t => t.id === 'integration_claude');
const codex = State.tasks.find(t => t.id === 'integration_codex');
assert.ok(codex);
assert.ok(!State.tasks.some(t => t.id === 'integration_vercel'));
const event = (name, extra = {}) => handleHook(island, { hook_event_name: name, coucou_agent: 'codex', cwd: 'C:\\work\\Codex Project', ...extra });
event('UserPromptSubmit', { prompt: 'Check the app' });
assert.equal(codex.state, 'thinking');
assert.equal(codex.steps.at(-1), 'Check the app');
event('PreToolUse', { tool_name: 'Bash', tool_input: { command: 'npm test' } });
assert.equal(codex.state, 'working');
event('Stop', { last_assistant_message: 'Tests passed' });
assert.equal(codex.state, 'finished');
assert.equal(codex.steps.at(-1), 'Tests passed');
event('UserPromptSubmit', { prompt: 'Next task' });
timers.shift()();
assert.equal(codex.state, 'thinking', 'Previous Stop must not idle a new task');
const claudeName = claude.name;
event('PermissionRequest', { request_id: 'test-codex', tool_name: 'Bash', tool_input: { command: 'npm test' } });
assert.equal(State.pendingApproval.agentId, 'integration_codex');
assert.equal(claude.name, claudeName, 'Codex must not rename the Claude pill');
assert.equal(codex.state, 'approval');
assert.deepEqual(acked, ['test-codex']);
event('PermissionRequest', { request_id: 'test-other' });
assert.deepEqual(declined, ['test-other']);
assert.equal(State.pendingApproval.requestId, 'test-codex');
State.pendingApproval = null;
State.paused = true;
event('PermissionRequest', { request_id: 'test-paused' });
assert.ok(declined.includes('test-paused'));
State.paused = false;
event('Interrupt');
assert.equal(codex.state, 'idle');
event('SessionEnd');
assert.equal(claude.name, claudeName);
console.log('PASS: Codex routing, steps, finish, stale timer, approval isolation, concurrent decline, pause, interrupt, session end, Vercel removal');

const live = (state, timestamp, extra = {}) => handleCodexLive(island, { sessionId: 'live-session', cwd: 'C:\\work\\Live Project', state, step: state, timestamp, ...extra });
live('working', '2026-10-01T18:00:00Z');
assert.equal(codex.state, 'working'); assert.equal(codex.sessionId, 'live-session');
event('SessionEnd', { session_id: 'old-session' });
assert.equal(codex.state, 'working', 'Old hook session end must not idle a live chat');
live('finished', '2026-10-01T17:59:00Z'); assert.equal(codex.state, 'working', 'Stale snapshot rejected');
live('thinking', '2026-10-01T18:00:01Z'); assert.equal(codex.state, 'thinking');
event('PermissionRequest', { request_id: 'live-human' }); assert.equal(codex.state, 'approval');
live('working', '2026-10-01T18:00:02Z'); assert.equal(codex.state, 'approval');
assert.equal(State.pendingApproval.requestId, 'live-human'); State.pendingApproval = null;
live('finished', '2026-10-01T18:00:03Z'); assert.equal(codex.state, 'finished');
live('working', '2026-10-01T18:00:04Z'); timers.at(-1)(); assert.equal(codex.state, 'working');
live('unknown', '2026-10-01T18:00:04Z'); assert.equal(codex.state, 'idle'); assert.equal(State.integrations.integration_codex.error, 'Live status unavailable');
live('idle', '2026-10-01T18:00:05Z'); assert.equal(codex.steps.length, 0);
live('finished', '2026-10-01T18:00:06Z');
assert.equal(codex.state, 'finished');
timers.at(-1)();
assert.equal(codex.state, 'idle', 'Completed turn returns to idle');
assert.deepEqual(codex.steps, [], 'Completed timeline must not keep the work ticker alive');
assert.equal(codex.stepIndex, 0);
assert.equal(codex.pillBadge, null);
assert.equal(codex.sessionId, 'live-session', 'Idle keeps the Open Codex target');
console.log('PASS: live lifecycle, stale snapshots, old SessionEnd isolation, human approval preservation, stale finish timer, unknown and connected idle');
